### ISSUE TITLE
运行错误，怎么解决

### ISSUE THREAD

**Issue by PKC278** [0x7FFFFF/Tsukiko#3]
插件加载中
共加载到0个插件
检测到您第一次使用本插件，正在初始化...
Traceback (most recent call last):
  File "run.py", line 58, in check_init
    open('.botinit', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '.botinit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 138, in <module>
    check_init()
  File "run.py", line 63, in check_init
    user.setUserPermission(admin_qq, 2)
  File "G:\下载\Tsukiko-main\Tsukiko-main\src\user.py", line 53, in setUserPermission
    raise UserNotFoundError
src.exception.UserNotFoundError

**Comment by lsicdl2d** [comment]
admin_qq设置了吗？

**Comment by PKC278** [comment]
设置了

**Comment by PKC278** [comment]
> admin_qq 设置了吗？

设置了

**Comment by lsicdl2d** [comment]
我的问题，等下改

**Comment by PKC278** [comment]
> 我的问题，等下改

修复完了吗

**Comment by lsicdl2d** [comment]
OK

**Comment by PKC278** [comment]
> OK

感谢大佬
